name: pytest

on:
  push:
    branches:
      - ec2deploy

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: Run tests
      run: |
        pytest test.py
  
  ec2deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: installing rsync
      run: sudo apt install rsync -y
    - name: create key to connect
      run: |
        echo "${{ secrets.AWSEC2_SSH_KEY }}" > key.pem
        chmod 400 key.pem
    - name: copy files to ec2
      run: |
        mkdir -p ~/.ssh/
        touch ~/.ssh/known_hosts
        ssh-keyscan ${{ secrets.AWSEC2_PUBLIC_IP }} > ~/.ssh/known_hosts
        sudo chmod 600 ~/.ssh/known_hosts
        rsync -e "ssh -i ./key.pem" ./* \
        ec2-user@${{ secrets.AWSEC2_PUBLIC_IP }}:./FlaskApp
    - name: restart FlaskApplication
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.AWSEC2_PUBLIC_IP }}
        username: ec2-user
        key_path: ./key.pem
        script: |
          pip install -r ./FlaskApp/requirements.txt
          sudo kill -9 \
          $(sudo netstat -tulnp | grep :5001 | awk '{print $NF}')
          nohup python3 ./FlaskApp/main.py &
          logout
